### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Kaptain-T** [zuri-training/Team96_Anima-lib#1]
Creating a logo that fits our chosen project name - Anibry

**Comment by hollahdaniel** [comment]
Done with the logo design, it is also available in svg.

**Comment by Kaptain-T** [comment]
Thank you. Issue completed and closed.

**Comment by hollahdaniel** [comment]
The logo was made with adobe illustration but the link to a clearer view is on Figma, please click below:
https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1720%3A7214
