### ISSUE TITLE
Designing the Home Page

### ISSUE THREAD

**Issue by Kaptain-T** [zuri-training/Team96_Anima-lib#2]
Homepage

**Comment by Henryola05** [comment]
Link & Image to Low-Fi Homepage
Link: https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib?node-id=2334%3A6625
![Homepage Low Fi](https://user-images.githubusercontent.com/60626256/182939210-746f48a2-03de-4c65-8fda-08a352993701.png)

**Comment by Kaptain-T** [comment]
Thanks a lot. Issue closed.

**Comment by Henryola05** [comment]
Updated images of Homepage Low-Fi Pages
![Low fi](https://user-images.githubusercontent.com/60626256/183890263-34ae5947-220a-4aec-b7b8-479fcc0667b8.png)
