### ISSUE TITLE
Design - User Research (painpoints and persona)

### ISSUE THREAD

**Issue by hollahdaniel** [zuri-training/Team96_Anima-lib#20]

**Comment by AdeLmd** [comment]
![User Persona](https://user-images.githubusercontent.com/105167645/182639818-91064a51-36f2-4685-8f7e-a4ac64c38a02.png)
![User Research](https://user-images.githubusercontent.com/105167645/182640157-8ea1565e-b817-44d5-8cbf-25882a027238.png)
 User Research (painpoints and persona) [Page](https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib?node-id=0%3A1)

**Comment by AdeLmd** [comment]
User Research (Painpoints and persona)
![User Journey](https://user-images.githubusercontent.com/105167645/183736685-0d03e4b9-c9a0-4b70-9bb1-2d345da3430a.png)
![User Persona](https://user-images.githubusercontent.com/105167645/183736803-eb823e9b-c1da-4e93-ae17-cc0c99b05b72.png)
User Research [Page](https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib?node-id=0%3A1)

**Comment by Kaptain-T** [comment]
Thanks! Image seen. Issue closed.
