### ISSUE TITLE
Documentation/Project brief

### ISSUE THREAD

**Issue by hollahdaniel** [zuri-training/Team96_Anima-lib#23]

**Comment by saye91** [comment]
Here is the link to the project brief.  [https://docs.google.com/document/d/1kcbERYRyC_Peh3p_UH5WyS2nxDLvmrxfup4V2oXBw2k/edit?usp=sharing](url)

**Comment by hollahdaniel** [comment]
![COVER PAGE](https://user-images.githubusercontent.com/42182236/183863188-325b0012-3741-4197-87f9-0d1be739e552.jpg)
![Database schema](https://user-images.githubusercontent.com/42182236/183863219-ec47a229-9dea-4fe0-9182-7978d5f73188.jpg)
![Design](https://user-images.githubusercontent.com/42182236/183863233-de6e997c-f34e-4230-9a92-4fc158c058ba.jpg)
![End](https://user-images.githubusercontent.com/42182236/183863242-97d66eb8-5dd9-4461-9589-e7937bbcc057.jpg)
![Feedbacks   deployment](https://user-images.githubusercontent.com/42182236/183863245-bd0db9b6-8b5b-43a3-9488-5ee5c18f85bf.jpg)
![project implimentation](https://user-images.githubusercontent.com/42182236/183863251-3c8a624b-0623-493a-a3a8-f4b89c00a001.jpg)
![Project scope](https://user-images.githubusercontent.com/42182236/183863263-58b0ef53-75a2-4f1b-93ca-d740b4bc34bd.jpg)
![SLIDE 1_ INTRODUCTION](https://user-images.githubusercontent.com/42182236/183863273-3555febf-83ac-4101-9976-143313360e82.jpg)
![Understanding the user](https://user-images.githubusercontent.com/42182236/183863290-62f2ed0b-dfd7-410c-8bec-ef4d511a9f45.jpg)
![User flow](https://user-images.githubusercontent.com/42182236/183863299-25af4ecd-faf6-4524-9633-3209b4661f59.jpg)

**Comment by hollahdaniel** [comment]
Work was done separately then later merged together for concrete/solid documentation.
It was another lovely experience to work on this aspect of the project.
