### ISSUE TITLE
Phase 1 project - slide creator

### ISSUE THREAD

**Issue by hollahdaniel** [zuri-training/Team96_Anima-lib#25]

**Comment by hollahdaniel** [comment]
I created the slide presentation and prototyped it with Figma which recorded on zoom with the presenters as our presentation.
Figma prototype link: https://www.figma.com/proto/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib?node-id=1436%3A7059&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1436%3A7059

**Comment by Kaptain-T** [comment]
Thank you. Issue completed.

**Comment by hollahdaniel** [comment]
![COVER PAGE](https://user-images.githubusercontent.com/42182236/183865401-ad7906c2-cf8a-4f08-8cae-a15936445d84.jpg)
![Database schema](https://user-images.githubusercontent.com/42182236/183865411-b7ad3471-78c9-40c1-8d21-e636fb85898d.jpg)
![Design](https://user-images.githubusercontent.com/42182236/183865418-8ee3eb64-f221-4fea-880c-bbf8cd5adabf.jpg)
![End](https://user-images.githubusercontent.com/42182236/183865420-692f4710-dda6-49c5-afe6-77eb7f249e8b.jpg)
![Feedbacks   deployment](https://user-images.githubusercontent.com/42182236/183865425-4f3a5470-ef4b-497a-b6c3-ae4da49a061f.jpg)
![project implimentation](https://user-images.githubusercontent.com/42182236/183865426-81b280d4-8db7-4612-ba40-01ce08e451c8.jpg)
![Project scope](https://user-images.githubusercontent.com/42182236/183865429-b3c62cd3-8556-4565-8e31-6e8c4d935a03.jpg)
![SLIDE 1_ INTRODUCTION](https://user-images.githubusercontent.com/42182236/183865435-4793064a-5f96-4888-9e7b-66e95fc41389.jpg)
![Understanding the user](https://user-images.githubusercontent.com/42182236/183865440-3de6dd15-6d04-4fb5-88ea-2da099771ca6.jpg)
![User flow](https://user-images.githubusercontent.com/42182236/183865449-32aea985-5ceb-44be-adda-505b3927bd9f.jpg)
