### ISSUE TITLE
Frontend - SignIn page

### ISSUE THREAD

**Issue by Kaptain-T** [zuri-training/Team96_Anima-lib#27]

**Comment by barbie-ema** [comment]
resolved this issue https://zuri-training.github.io/Team96_Anima-lib/Frontend/login.html
codes https://github.com/barbie-ema/Team96_Anima-lib/blob/main/Frontend/login.html

also resolved forgot.html
https://zuri-training.github.io/Team96_Anima-lib/Frontend/forgot.html
code https://github.com/barbie-ema/Team96_Anima-lib/blob/main/Frontend/forgot.html
