### ISSUE TITLE
Designing the Homepage

### ISSUE THREAD

**Issue by Kaptain-T** [zuri-training/Team96_Anima-lib#3]
Homepage

**Comment by Henryola05** [comment]
Link and image of Hi-Fi Homepage design
Link: https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib?node-id=1876%3A9055
![Homepage](https://user-images.githubusercontent.com/60626256/182929459-d3193e3e-8d5c-48f9-ae49-591273a856f4.png)

**Comment by Kaptain-T** [comment]
Thanks man. Issue closed.

**Comment by Henryola05** [comment]
Updated image of the homepage hi-fi and responsive screen
![hifi](https://user-images.githubusercontent.com/60626256/183889490-aa3b1bf2-2857-40c4-bb77-fa3ed4aed5cb.png)
![Hifi responsive](https://user-images.githubusercontent.com/60626256/183889591-82f97028-7922-4baf-a46c-094ee1c2f938.png)
