### ISSUE TITLE
Design - Landing page

### ISSUE THREAD

**Issue by Kaptain-T** [zuri-training/Team96_Anima-lib#6]
Designing the landing page

**Comment by TeeOverflow** [comment]
Landing page LoFi designs done.

![image](https://user-images.githubusercontent.com/105021356/182842216-95d4b4e7-ce0c-42ad-876e-0d96b05b6795.png)
![landing](https://user-images.githubusercontent.com/105021356/182842406-7dee1d2b-511e-4f46-82a0-5024541afa0f.jpg)
https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib?node-id=650%3A4

**Comment by SisiVero** [comment]
Responsive design (Tablet view) for landing page completed.
https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1734%3A8564

**Comment by Kaptain-T** [comment]
Nicely done. Thanks. Issue closed.
