### ISSUE TITLE
Design - Forgot password page

### ISSUE THREAD

**Issue by Kaptain-T** [zuri-training/Team96_Anima-lib#65]

**Comment by Evelyn640** [comment]
Was great working together!
![Forgot Password](https://user-images.githubusercontent.com/105177112/183752253-5ddd58a1-e5e8-4f80-9c97-07a7cb70ec39.png)

**Comment by abi-holla** [comment]
Good teamwork experience.
![Reset Password](https://user-images.githubusercontent.com/105369016/183753290-eb905c0c-e5a6-4034-b65f-11473a119ef3.png)

Forgot password page Lo-Fi: https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1147%3A5335

**Comment by Kaptain-T** [comment]
Thanks. Issue closed.
