### ISSUE TITLE
Design - Reset password pages with successful, error and notification states

### ISSUE THREAD

**Issue by Kaptain-T** [zuri-training/Team96_Anima-lib#66]

**Comment by Evelyn640** [comment]
[Reset Password](https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1434%3A6677)
![Reset Password Error](https://user-images.githubusercontent.com/105177112/183753483-13df2fba-b2d4-462c-9e18-0e58f177926f.png)


[Reset password Successful](https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1473%3A4847)![Reset Password Successful](https://user-images.githubusercontent.com/105177112/183753500-0d18cdd2-7e4d-4fa5-bd53-1d2ab95378be.png)

[Reset Password Notification](https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1473%3A4894)![Reset Password-1](https://user-images.githubusercontent.com/105177112/183753508-4fa896fb-a990-46de-8abc-30e92103a9f8.png)

[Reset Password Error](https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1473%3A4869)![Reset Password](https://user-images.githubusercontent.com/105177112/183753522-f8c8cdca-a6d6-4397-abee-08dbbfaf933e.png)

**Comment by abi-holla** [comment]
Hitch-free process.
Reset password page: https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1147%3A5335
![Reset Password](https://user-images.githubusercontent.com/105369016/183755640-fac054e2-e1a0-4f69-bab7-4ad786343c36.png)

Reset password successful state page: https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1434%3A6914
![Successful Reset Password](https://user-images.githubusercontent.com/105369016/183755773-f258eac8-eccc-4120-be9c-af7ef5b2c1be.png)

Reset password error state page: https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1436%3A4268
![Error Reset Password](https://user-images.githubusercontent.com/105369016/183755959-8830b7ba-5777-42e8-9f12-935a1b601eaf.png)

Reset password notification state page: https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1434%3A6946
![Information Forgot Password](https://user-images.githubusercontent.com/105369016/183756111-0f7ac2d5-2bff-491f-99fe-07979cb150ee.png)

**Comment by Kaptain-T** [comment]
Thanks. Issue closed.
