### ISSUE TITLE
Design - Sign up prompt

### ISSUE THREAD

**Issue by Kaptain-T** [zuri-training/Team96_Anima-lib#67]

**Comment by Evelyn640** [comment]
https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1434%3A6749![Sign Up Prompt](https://user-images.githubusercontent.com/105177112/183755024-e3b2c66d-b1a5-4b40-852e-9d4af1450a01.png)

**Comment by Evelyn640** [comment]
Teamwork was great
[Sign Up Prompt](https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1434%3A6749)
![Sign Up Prompt](https://user-images.githubusercontent.com/105177112/183755574-09bd40e6-3a88-477d-b488-c2ea1aed66a0.png)

**Comment by abi-holla** [comment]
Smooth process.
SignUp Prompt Lo-Fi: https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1145%3A5150
![Sign Up Prompt](https://user-images.githubusercontent.com/105369016/183756802-9593f638-6332-47ba-81da-fae335d9c5b3.png)

**Comment by Kaptain-T** [comment]
Thank you. Issue closed.
