### ISSUE TITLE
Design - Landing Page

### ISSUE THREAD

**Issue by Kaptain-T** [zuri-training/Team96_Anima-lib#7]
Designing the landing page

**Comment by TeeOverflow** [comment]
Landing page HiFi design is done and currently being reviewed. Figma link to the page coming right up.

**Comment by SisiVero** [comment]
Landing page responsive pages ( Mobile and iPad) Hifi and Lowfi all done and currently under review.

**Comment by TeeOverflow** [comment]
Landing page HiFi designs done.

![image](https://user-images.githubusercontent.com/105021356/182844134-b7add485-8d37-4549-b645-3ae812e78cd7.png)
https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib?node-id=1413%3A4095

**Comment by Kaptain-T** [comment]
Thank you. Issue closed.

**Comment by SisiVero** [comment]
Link to responsive Landing page ( Tablet and Mobile)
https://www.figma.com/file/gFDREjDvch3LiCT3x1jmRN/Team-96_Anima-lib-O?node-id=1599%3A4747
